### PR TITLE
go 1.9.7

### PR DESCRIPTION
**Pull request by lpdyck**
for https://github.com/toggl/backend/issues/6931

### CODE REVIEW

**Comment by lpdyck** [comment]
No, not missing, someone made it a submodule. But since I am not the only one having issues with that, I will fix it.

**Comment by fdelbos** [comment]
@lpdyck it's easy to fix, just put the sources in the directory (without the git files), just like the other dependencies. And add them to the repo. Thanks!

**Comment by lpdyck** [comment]
The trick was I had to remove the directory and `git add` that change before putting the sources there. Thanks for the pointer, though, I wouldn't have known to get rid of the git files and probably made the mess worse.

**Comment by fdelbos** [comment]
@lpdyck thanks for doing it!

**Pull request merged**
